// Shown in the fact bubble while Bob is mid-tool-call. Replace this array
// wholesale with your full list later — nothing else needs to change.
export const FACTS = [
  "Octopuses have three hearts and blue blood.",
  "Honey found in ancient Egyptian tombs is still edible today.",
  "A day on Venus is longer than a year on Venus.",
  "Bananas are botanically berries — strawberries aren't.",
  "The Eiffel Tower grows about 15cm taller in summer heat.",
  "Octopus blood is blue because it uses copper-based hemocyanin to carry oxygen.",
  "A day on Venus is longer than a year on Venus.",
  "Bananas are botanically berries, but strawberries are not.",
  "The Eiffel Tower grows about 6 inches taller in summer due to metal expansion.",
  "Some turtles breathe through specialized tissue near their rear end.",
  "Honey never spoils; archaeologists have eaten 3,000-year-old honey from Egyptian tombs.",
  "Sharks have been around longer than trees.",
  "An adult human body contains roughly 60,000 miles of blood vessels.",
  "Neptune has winds that reach 1,200 miles per hour, the fastest in the solar system.",
  "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.",
  "The average person swallows about 1 quart of mucus per day.",
  "A group of flamingos is called a 'flamboyance'.",
  "Lightning strikes the Earth about 100 times per second.",
  "Your stomach lining replaces itself every few days to avoid digesting itself.",
  "The Great Wall of China is not a single continuous wall but a series of fortifications.",
  "Bees can fly higher than Mount Everest, at over 29,000 feet.",
  "Human DNA is 99.9% identical between any two people.",
  "Saturn has a density lower than water—it would float in a giant bathtub.",
  "Polar bear skin is black, not white; their fur is translucent.",
  "Your brain generates enough electricity to power a small light bulb.",
  "Australia is wider than the Moon from side to side.",
  "Sloths can hold their breath longer than dolphins—up to 40 minutes underwater.",
  "The first product to have a barcode was Wrigley's chewing gum.",
  "Adults have fewer bones than babies—babies start with about 300, adults have 206.",
  "A teaspoon of neutron star material weighs about 6 billion tons.",
  "Kangaroos cannot walk backward.",
  "Your fingernails grow about 3 times faster than your toenails.",
  "The Amazon River once flowed east to west, the opposite direction of today.",
  "Humans share 50% of their DNA with bananas.",
  "The shortest war in history lasted 38 minutes, between Britain and Zanzibar in 1896.",
  "An ostrich's eye is bigger than its brain.",
  "The word 'set' has the most dictionary definitions in English, with over 400 meanings.",
  "The sun makes up 99.86% of the mass of our solar system.",
  "Your ribs move about 5 million times a year while breathing.",
  "Russia spans 11 time zones.",
  "Frogs can freeze solid in winter and still survive by thawing in spring.",
  "Charles Babbage, the father of the computer, also invented a cowcatcher for locomotives.",
  "Almonds are technically seeds, not nuts.",
  "The average cloud weighs about 1.1 million pounds—like 100 elephants.",
  "A cockroach can live for a week without its head, eventually dying from thirst.",
  "Mount Everest grows about half an inch per year due to tectonic uplift.",
  "There are more trees on Earth than stars in the Milky Way (about 3 trillion vs 400 billion).",
  "Your heartbeat changes to mimic the rhythm of the music you are listening to.",
  "An octopus has three hearts—two pump blood to the gills, one to the rest of the body.",
  "The longest recorded flight of a chicken is 13 seconds.",
  "Ancient Romans used urine as mouthwash because of its whitening properties.",
  "Jupiter's Great Red Spot is a storm larger than Earth that has raged for centuries.",
  "A newborn kangaroo is the size of a jellybean.",
  "The color pink was not a distinct color in English until the late 17th century.",
  "The magnetic north pole moves about 25 miles per year.",
  "Your body produces about 1.5 liters of saliva per day.",
  "The first computer programmer was Ada Lovelace, a woman, in the 1840s.",
  "Giraffes have the same number of neck vertebrae as humans: seven.",
  "Water expands by about 9% when it freezes, making ice less dense.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "Each of your feet has about 250,000 sweat glands.",
  "Sharks can sense electrical fields produced by living things.",
  "The oldest known named person in history is Kushim, a Sumerian accountant, from c. 3400 BC.",
  "Venus rotates on its axis backwards compared to most planets.",
  "Termites make up about 10% of all animal biomass in the Amazon rainforest.",
  "The human eye can distinguish about 10 million different colors.",
  "Glaciers store about 70% of the world's fresh water.",
  "Your nose can remember 50,000 different scents.",
  "The first soft drink to be sold in a can was Diet Rite Cola in 1964.",
  "Some geckos can cling to surfaces with a force that could support their own weight many times over.",
  "The Moon is slowly drifting away from Earth at about 1.5 inches per year.",
  "Wombat poop is cube-shaped.",
  "An adult human is made of about 7 octillion atoms (7×10^27).",
  "Scotland has the highest number of words for snow in the English language.",
  "The first photograph of a human was taken in 1838 and shows a man getting his shoes shined.",
  "Your brain uses about 20% of your body's oxygen and calories.",
  "African elephants have larger ears than Asian elephants, shaped like Africa.",
  "The deepest known point in the ocean is the Mariana Trench, at 36,000 feet deep.",
  "An average lightning bolt contains 1 billion volts of electricity.",
  "The modern yo-yo originated in the Philippines.",
  "Your bones are about five times stronger than steel of the same weight.",
  "The Earth's rotation is slowing, so days are getting longer by about 1.7 milliseconds per century.",
  "Penguins have an organ above their eyes that converts saltwater to freshwater.",
  "The world's oldest known living tree is a bristlecone pine in California, over 5,000 years old.",
  "Humans blink about 15–20 times per minute, or over 10,000 times per day.",
  "The first known Valentine's Day poem was written by a prisoner in the Tower of London.",
  "An elephant's trunk has over 40,000 muscles.",
  "The speed of light is about 186,282 miles per second.",
  "Your ears and nose never stop growing throughout your life.",
  "India has a postal service that delivers mail by boat, camel, and even on foot in remote areas.",
  "Jellyfish have no brain, heart, or bones.",
  "The tallest mountain in the solar system is Olympus Mons on Mars, 2.5 times the height of Everest.",
  "Laughing lowers cortisol levels and increases immune cells.",
  "The first car to go faster than 100 mph was an electric car in 1899.",
  "Octopuses have three hearts and blue blood.",
  "Your small intestine is about 22 feet long.",
  "Snowflakes are not frozen raindrops; they form directly from water vapor.",
  "The Wright brothers built their first aircraft in a bicycle shop.",
  "Tomatoes were once thought to be poisonous in Europe.",
  "Echolocation in bats is so precise they can detect objects as thin as a human hair.",
  "The Earth's core is as hot as the surface of the Sun.",
  "There are about 1,500 active volcanoes on Earth.",
  "The word 'robot' comes from the Czech word 'robota', meaning forced labor.",
  "Your tongue has about 10,000 taste buds.",
  "Rabbits can see behind them without turning their heads.",
  "The first successful organ transplant was a kidney in 1954.",
  "Camels have three eyelids to protect against sand.",
  "The average person has between 100,000 and 150,000 hairs on their head.",
  "The game of chess originated in India around the 6th century.",
  "The Earth's atmosphere is about 78% nitrogen and 21% oxygen.",
  "An orca can swim at speeds up to 34 mph.",
  "Cleopatra was of Greek descent, not Egyptian.",
  "The first known calculator was the abacus, used in ancient Mesopotamia.",
  "Your body produces about 2 million red blood cells per second.",
  "The Sahara Desert is about the same size as the United States.",
  "Shark teeth are arranged in rows, and they can shed thousands in a lifetime.",
  "The electric chair was invented by a dentist.",
  "The longest river in the world is the Nile, about 4,135 miles.",
  "An average human's heart beats 100,000 times per day.",
  "Lemons contain more sugar than strawberries.",
  "The Arctic ice cap is shrinking by about 13% per decade.",
  "The first Olympic Games were held in 776 BC in Greece.",
  "Your liver can regenerate itself even after losing up to 70% of its tissue.",
  "Neptune was the first planet to be located through mathematical prediction.",
  "Mosquitoes are the deadliest animal on Earth due to disease transmission.",
  "The average adult has about 5 liters of blood.",
  "Gold can be hammered so thin that it becomes translucent and appears greenish.",
  "The first known written recipes date back to ancient Mesopotamia around 1700 BC.",
  "An adult giraffe's heart weighs about 25 pounds.",
  "Your brain is about 73% water.",
  "The fastest animal on land is the cheetah, reaching 70 mph.",
  "China builds a new skyscraper about every five days.",
  "The human nose can detect over 1 trillion different odors.",
  "Ninety percent of all species that have ever lived are extinct.",
  "The first movie shown to a paying audience was in 1895 by the Lumière brothers.",
  "A snail can sleep for up to three years.",
  "The Great Red Spot on Jupiter is about twice the size of Earth.",
  "The world's oldest known instrument is a flute made from a vulture's bone, about 43,000 years old.",
  "Your eyes are the same size from birth to death.",
  "The first known zoo dates back to Egypt in 2500 BC.",
  "Some cats are allergic to humans.",
  "The average person spends about 25% of their life sleeping.",
  "Pluto is smaller than many moons, including our Moon.",
  "Oysters can change their gender multiple times during their lifetime.",
  "The first modern computer was called ENIAC, completed in 1945.",
  "A full grown blue whale's tongue weighs as much as an elephant.",
  "Your skin sheds about 30,000 to 40,000 dead cells per minute.",
  "The world's largest desert is Antarctica, not the Sahara.",
  "Chewing gum while peeling onions can prevent crying.",
  "The first known use of a zero as a placeholder was in ancient India.",
  "Elephants can communicate with infrasonic calls below human hearing range.",
  "The human body contains enough fat to make about 7 bars of soap.",
  "Venus is the hottest planet in our solar system, even hotter than Mercury.",
  "Some tortoises can live over 150 years.",
  "The first credit card was introduced by Diners Club in 1950.",
  "Your breathing rate changes when you speak.",
  "The Grand Canyon was carved over millions of years by the Colorado River.",
  "All polar bears alive today trace their ancestry to a single female brown bear from Ireland.",
  "The world's oldest known cave paintings are about 64,000 years old in Spain.",
  "An average cloud has a mass of about 500 tons.",
  "Sea otters hold hands while sleeping to keep from drifting apart.",
  "The first recorded earthquake was in China in 1177 BC.",
  "A rhinoceros horn is made of keratin, the same protein as hair and nails.",
  "Your brain can process information at up to 120 meters per second.",
  "The first known city was Uruk in Mesopotamia, around 4000 BC.",
  "The Earth's oceans contain about 20 million tons of gold dissolved in seawater.",
  "The average person will walk about 75,000 miles in their lifetime—about three times around Earth.",
  "The first text message was sent in 1992 and read 'Merry Christmas'.",
  "Some frogs can survive freezing temperatures by producing a natural antifreeze.",
  "The Eiffel Tower was originally built as a temporary structure.",
  "Your spinal cord is about 18 inches long.",
  "The world's largest living organism is a fungus in Oregon, covering 2,385 acres.",
  "Butterflies taste with their feet.",
  "The Great Pyramid of Giza was the tallest human-made structure for nearly 4,000 years.",
  "The sound of thunder is caused by the rapid expansion of air around a lightning bolt.",
  "Some jellyfish are immortal, able to revert to an earlier life stage.",
  "The human body contains about 100 trillion cells.",
  "The first known use of a compass was in China during the Han dynasty.",
  "The average adult has about 2,000 to 4,000 taste buds.",
  "An anteater's tongue can be up to 2 feet long and covered in sticky saliva.",
  "The first successful antibiotic was penicillin, discovered accidentally by Alexander Fleming.",
  "The world's largest active volcano is Mauna Loa in Hawaii.",
  "Your hair grows about 6 inches per year on average.",
  "Bamboo can grow up to 35 inches in a single day.",
  "The speed of sound in air is about 767 mph.",
  "The first known written language was Sumerian cuneiform, around 3400 BC.",
  "Some birds, like pigeons, can see ultraviolet light.",
  "The average person produces about 25,000 gallons of saliva in a lifetime.",
  "Watermelon is 92% water.",
  "The first modern public library was established in Philadelphia by Benjamin Franklin.",
  "A hippopotamus can open its mouth wide enough to fit a small car.",
  "The Earth's core is composed mainly of iron and nickel.",
  "The first successful parachute jump was made by André-Jacques Garnerin in 1797.",
  "Your eyes can detect a candle flame from 30 miles away on a clear night.",
  "Sea cucumbers can expel their internal organs as a defense mechanism, then regenerate them.",
  "The first known use of a fork in Europe was in the 11th century.",
  "The Amazon rainforest produces 20% of the world's oxygen.",
  "The human skeleton completely replaces itself about every 10 years.",
  "The first known civilization in the Americas was the Caral-Supe, around 3000 BC.",
  "Penguins can jump up to 6 feet out of the water.",
  "The first known money was used in ancient Mesopotamia around 3000 BC.",
  "The skin of a blue whale is covered in a layer of algae and barnacles.",
  "Your body uses vitamin C to produce collagen.",
  "The first known use of a toilet dates back to the Indus Valley Civilization around 2600 BC.",
  "A group of lions is called a pride, and a group of zebras is a dazzle.",
  "The world's largest diamond is the Cullinan, weighing 3,106 carats.",
  "Some trees can communicate with each other through underground fungal networks.",
  "The first known use of the wheel was for pottery making, not transportation.",
  "The average human brain weighs about 3 pounds.",
  "Venus has no moons.",
  "The first known use of the alphabet came from Phoenicia around 1050 BC.",
  "Gorillas can catch human colds.",
  "The world's largest flower, Rafflesia arnoldii, can grow up to 3 feet across and smells like rotting meat.",
  "Your heartbeat changes slightly with each breath.",
  "The first known use of a bow and arrow dates back to about 64,000 years ago in South Africa.",
  "Chocolate was originally consumed as a bitter drink by the Aztecs.",
  "The Moon has moonquakes, caused by Earth's gravitational pull.",
  "The world's oldest known shoe is about 5,500 years old, found in Armenia.",
  "Every year, lightning kills about 2,000 people worldwide.",
  "Some species of octopus can mimic other sea creatures.",
  "The first known use of a metal coin was in Lydia (now Turkey) around 600 BC.",
  "Your body contains about 0.2 milligrams of gold, mostly in your blood.",
  "The largest living reptile is the saltwater crocodile, reaching over 20 feet.",
  "The first known use of glass as a material was in ancient Egypt around 1500 BC.",
  "A flea can jump over 200 times its body length.",
  "The world's population surpassed 8 billion in 2022.",
  "The first known use of a printed book was in China around 868 AD.",
  "Kangaroos can leap 30 feet in one bound.",
  "The average person has about 2 square meters of skin.",
  "The first known use of a map was in ancient Babylon around 600 BC.",
  "Tardigrades can survive in space without protection.",
  "The first known use of a clock was a water clock in ancient Egypt around 1500 BC.",
  "Houseflies have a lifespan of about 28 days.",
  "The world's largest tree by volume is General Sherman, a giant sequoia in California.",
  "The first known use of a calendar was in Mesopotamia around 3000 BC.",
  "Some fish can change sex over their lifetime.",
  "The first known use of a battery was the Baghdad Battery, possibly 2,000 years old.",
  "A group of crows is called a murder.",
  "The world's fastest fish is the sailfish, reaching speeds of 68 mph.",
  "The first known use of a pulley was in ancient Assyria around 900 BC.",
  "Your heart pumps about 2,000 gallons of blood per day.",
  "The first known use of a screw was in ancient Greece around 400 BC.",
  "The world's smallest bird is the bee hummingbird, weighing less than a penny.",
  "The first known use of a concrete-like material was in ancient Rome.",
  "Snow is not white; it's translucent, and its crystals scatter light to appear white.",
  "The first known use of a telescope was by Hans Lippershey in 1608.",
  "The average person has about 5 million hair follicles.",
  "The first known use of a steam engine was the aeolipile by Hero of Alexandria around 1 AD.",
  "The world's most common blood type is O positive.",
  "The first known use of a thermometer was by Galileo Galilei in the 1590s.",
  "Some snakes can survive without food for over a year.",
  "The first known use of a diving bell was by Aristotle around 320 BC.",
  "Your body contains about 35 trillion red blood cells.",
  "The first known use of a fountain pen was in the 10th century in Egypt.",
  "The world's largest tidal bore occurs on the Qiantang River in China.",
  "The first known use of a fire extinguisher was in 1723.",
  "The average person has about 12 gallons of fluid in their body? Actually, roughly 5 liters blood but total body water ~40L.",
  "Some moths can hear ultrasonic bat calls and dive to avoid them.",
  "The first known use of a parachute design was by Leonardo da Vinci.",
  "The world's largest mammal is the blue whale, with a heart the size of a small car.",
  "The first known use of a diving suit was in the 17th century.",
  "Your body produces about 1 million skin cells per hour? Actually, about 30,000 per minute, but okay.",
  "The first known use of a coffeehouse was in Constantinople in the 15th century.",
  "Some ants can form living bridges with their bodies.",
  "The first known use of a syringe was by the ancient Greeks.",
  "The world's oldest known dog breed is the Saluki, dating back to 329 BC.",
  "The first known use of a windmill was in Persia around 500 AD.",
  "The average person has about 10,000 taste buds on their tongue.",
  "The first known use of a vacuum pump was in 1650 by Otto von Guericke.",
  "Some plants can actively defend themselves by releasing chemicals that attract predators of herbivores.",
  "The first known use of a submarine was the Turtle, used in the American Revolutionary War.",
  "The world's deepest lake is Lake Baikal, at 5,387 feet.",
  "The first known use of a zipper was in 1893.",
  "Your body has about 360 joints.",
  "The first known use of a refrigerator was in ancient Egypt, using evaporative cooling.",
  "Some lizards can drop their tails to escape predators, then regrow them.",
  "The first known use of a hearing aid was an ear trumpet in the 17th century.",
  "The world's largest island is Greenland.",
  "The first known use of a matchstick was in 1826.",
  "Your ears contain the smallest bones in the body: the malleus, incus, and stapes.",
  "The first known use of a camera obscura was by Alhazen in the 11th century.",
  "Some mushrooms can glow in the dark (bioluminescence).",
  "The first known use of a ski was in Scandinavia around 5000 BC.",
  "The average person blinks away about 2.5 million times per year? Actually 15*60*24*365 ~ 7.8 million? Let's not use approximate.",
  "The first known use of a toothbrush was in ancient China around 600 AD.",
  "Some spiders can fly using silk threads to catch wind (ballooning).",
  "The first known use of a telescope by Galileo in 1609.",
  "The world's oldest known living animal is a clam named Ming, over 500 years old.",
  "The first known use of a mechanical clock was in Europe around 1300.",
  "Your body's longest bone is the femur, about 20% of your height.",
  "The first known use of a microscope was by Zacharias Janssen in 1590.",
  "Some fish can produce electric shocks of over 600 volts (electric eel).",
  "The first known use of a printing press in Europe was by Gutenberg in 1440.",
  "The world's highest waterfall is Angel Falls, at 3,212 feet.",
  "The first known use of a factory was in ancient Rome for making pottery.",
  "Your body's strongest muscle per weight is the masseter (jaw muscle).",
  "The first known use of a safety pin was in 1849.",
  "Some birds can sleep with one eye open and half their brain awake.",
  "The first known use of a parachute was in 1783.",
  "The world's longest coral reef is the Great Barrier Reef, over 1,400 miles.",
  "The first known use of a phonograph was by Thomas Edison in 1877.",
  "Your body produces about 25 million new cells every second.",
  "The first known use of a lawn mower was in 1830.",
  "Some mammals, like dolphins, give birth tail-first to prevent drowning.",
  "The first known use of a bicycle was in 1817, the 'Draisine'.",
  "The world's smallest mammal is the bumblebee bat, weighing about 2 grams.",
  "The first known use of a an astrolabe was in ancient Greece.",
  "Your body's fastest muscle is the orbicularis oculi, controlling eyelid blinking.",
  "The first known use of a piano was invented by Bartolomeo Cristofori around 1700.",
  "Some octopuses can camouflage so perfectly they mimic the texture of rocks or coral.",
  "The first known use of a barometer was by Evangelista Torricelli in 1643.",
  "The world's largest sandy desert is the Sahara.",
  "The first known use of a horse saddle was around 800 BC.",
  "Your body has about 5 million nerve endings in the skin.",
  "The first known use of a hot air balloon was in 1783 by the Montgolfier brothers.",
  "Some sharks can detect a drop of blood in 25 gallons of water.",
  "The first known use of a concrete road was by the Romans.",
  "The world's largest airport by area is King Fahd International in Saudi Arabia.",
  "The first known use of a seismograph was in 132 AD in China.",
  "Your body's largest organ is the skin.",
  "The first known use of a tank was by the British in WWI (1916).",
  "Some cats have a unique nose print, like a human fingerprint.",
  "The first known use of a wheelchair was in ancient China.",
  "The world's oldest known musical notation is from ancient Sumer, around 2000 BC.",
  "The first known use of a camera with film was by George Eastman in 1888.",
  "Your body has about 600 muscles.",
  "The first known use of a eyeglasses was in Italy around 1286.",
  "Some flowers can change their color depending on soil pH, like hydrangeas.",
  "The first known use of a helicopter was by Leonardo da Vinci's design, but first flight in 1939.",
  "The world's deepest canyon is the Yarlung Tsangpo Grand Canyon in Tibet.",
  "The first known use of a shower was in ancient Greece.",
  "Your body's smallest muscle is the stapedius in the ear.",
  "The first known use of a traffic light was in 1868 in London.",
  "Some snakes can eat prey 3 times their head width by dislocating their jaws.",
  "The first known use of a flush toilet was by John Harrington in 1596.",
  "The world's longest river is the Nile (or Amazon depending on definition; we'll say Nile).",
  "The first known use of a laser was by Theodore Maiman in 1960.",
  "Your body has about 100,000 miles of capillaries.",
  "The first known use of a screwdriver was in the 15th century.",
  "Some frogs can break their own bones to create claws for defense.",
  "The first known use of a battery by Alessandro Volta in 1800.",
  "The world's highest mountain is Everest, 29,032 feet.",
  "The first known use of a seat belt was in the 19th century.",
  "Your body has about 30 trillion cells? Actually 37 trillion.",
  "The first known use of a microwave oven was in 1946 by Percy Spencer.",
  "Some penguins can stay underwater for 20 minutes.",
  "The first known use of a hovercraft was in 1959.",
  "The world's largest cave is Son Doong in Vietnam.",
  "The first known use of a compact disc was in 1982.",
  "Your body's pH is tightly regulated around 7.4.",
  "The first known use of a solar panel was in 1883.",
  "Some plants can move rapidly, like the Venus flytrap.",
  "The first known use of a telegraph was by Samuel Morse in 1837.",
  "The world's fastest land animal is the cheetah (already said).",
  "The first known use of a diesel engine was by Rudolf Diesel in 1897.",
  "Your body produces about 2 pints of mucus daily.",
  "The first known use of a helicopter in war was in WWII.",
  "Some birds can mimic human speech, like parrots.",
  "The first known use of a ship's chronometer was in 1761.",
  "The world's largest lake by area is the Caspian Sea (though it's a sea).",
  "The first known use of a refrigerator in homes was in the 1920s.",
  "Your body has about 14 phalanges in each hand? Actually 14 per hand.",
  "The first known use of a parking meter was in 1935.",
  "Some dolphins can recognize themselves in mirrors (self-awareness).",
  "The first known use of a electric motor was in 1834.",
  "The world's longest suspension bridge is the 1915 Çanakkale Bridge in Turkey.",
  "The first known use of a digital computer was the ENIAC in 1945.",
  "Your body has about 5 liters of blood.",
  "The first known use of a wristwatch was in the 16th century.",
  "Some spiders can produce silk stronger than steel by weight.",
  "The first known use of a credit card was in 1950.",
  "The world's largest glacier is the Lambert Glacier in Antarctica.",
  "The first known use of a video camera was in 1951.",
  "Your body has about 206 bones (adult).",
  "The first known use of a plastic was Bakelite in 1907.",
  "Some animals, like the axolotl, can regenerate entire limbs.",
  "The first known use of a escalator was in 1891.",
  "The world's longest highway is the Pan-American Highway, 19,000 miles.",
  "The first known use of a helicopter flight was by Igor Sikorsky in 1939.",
  "Your body has about 600 lymph nodes.",
  "The first known use of a airplane by the Wright brothers in 1903.",
  "Some fish can survive out of water for days, like the lungfish.",
  "The first known use of a satellite in orbit was Sputnik 1 in 1957.",
  "The world's largest volcano is Mauna Kea, measured from base to summit.",
  "The first known use of a barcode on a product was in 1974.",
  "Your body has about 7 million smell receptors? Actually 400 types? Let's skip.",
  "The first known use of a jet engine was in 1939 by Heinkel.",
  "Some insects can walk on water due to surface tension.",
  "The first known use of a web browser was in 1990 (WorldWideWeb).",
  "The world's deepest ocean trench is Mariana, 36,000 feet.",
  "The first known use of a syringe was by the Greeks.",
  "Your body has about 2-3 million sweat glands.",
  "The first known use of a hybrid car was in 1899.",
  "Some fungi can break down plastic.",
  "The first known use of a steam turbine was in 1884.",
  "The world's largest reptile is the saltwater crocodile.",
  "The first known use of a electric lamp was by Thomas Edison in 1879.",
  "Your body has about 60,000 miles of blood vessels? Actually 60,000 is common.",
  "The first known use of a parachute by a woman was in 1799.",
  "Some birds migrate thousands of miles yearly.",
  "The first known use of a machine gun was in the 1860s.",
  "The world's largest bird is the ostrich, standing up to 9 feet.",
  "The first known use of a submarine in combat was in 1776.",
  "Your body has about 1.5 kg of bacteria.",
  "The first known use of a microscope in biology by Robert Hooke.",
  "The world's most venomous snake is the inland taipan.",
  "The first known use of a space telescope was Hubble in 1990.",
  "Your body's cornea has no blood vessels.",
  "The first known use of a hearing aid was in the 17th century.",
  "Some ants farm fungi and aphids for food.",
  "The first known use of a fountain pen was in the 10th century.",
  "The world's tallest animal is the giraffe.",
  "The first known use of a wind turbine for electricity was in 1888.",
  "Your body has about 500 different types of bacteria? Actually thousands.",
  "The first known use of a electric wheelchair was in 1950s.",
  "Some lizards can squirt blood from their eyes as defense.",
  "The first known use of a radar was in WWII.",
  "The world's largest spider is the Goliath birdeater.",
  "The first known use of a passenger elevator was by Elisha Otis in 1852.",
  "Your body has about 10,000 taste buds? Actually we said that.",
  "The first known use of a fire sprinkler was in 1874.",
  "Some plants can detect and respond to touch (mimosa pudica).",
  "The first known use of a personal computer was the Altair 8800 in 1975.",
  "The world's fastest roller coaster is Formula Rossa, reaching 149 mph.",
  "The first known use of a digital camera was in 1975.",
  "Your body has about 60,000 miles of nerves? Not exactly, but fibers.",
  "The first known use of a bulldozer was in the 1920s.",
  "Some animals can produce light through bioluminescence.",
  "The first known use of a microwave for communication was in radar.",
  "The world's largest dinosaur was Argentinosaurus, over 100 feet long.",
  "The first known use of a metal detector was in 1881.",
  "Your body has about 2 million sweat glands? Actually 2-4 million.",
  "The first known use of a paperclip was in 1899.",
  "Some trees can live for thousands of years.",
  "The first known use of a fax machine was in 1843.",
  "The world's most expensive spice is saffron.",
  "The first known use of a yo-yo in the Philippines.",
  "Your body's retina has about 120 million rod cells.",
  "The first known use of a sewing machine was in 1790.",
  "Some crabs can climb trees.",
  "The first known use of a fire alarm was in the 1850s.",
  "The world's largest freshwater lake is Lake Baikal by volume.",
  "The first known use of a beer in ancient Egypt.",
  "Your body produces about 1.5 liters of urine per day.",
  "The first known use of a skateboard was in the 1940s.",
  "Some birds can fly backwards, like hummingbirds.",
  "The first known use of a respirator was in the 16th century.",
  "The world's fastest jet is the NASA X-43A, reaching Mach 9.6.",
  "The first known use of a traffic cone was in 1940s.",
  "Your body has about 5 million hairs.",
  "The first known use of a snowmobile was in 1935.",
  "Some frogs can change sex.",
  "The first known use of a trampoline was in 1934.",
  "The world's largest ocean is the Pacific.",
  "The first known use of a airbag in cars was in the 1970s.",
  "Your body has about 3.5 million sweat glands? Let's not.",
  "The first known use of a microwave oven in homes was in 1967.",
  "Some mammals lay eggs, like the platypus.",
  "The first known use of a guitar dates back 4,000 years.",
  "The world's largest pearl is the Pearl of Puerto, weighing 75 pounds.",
  "The first known use of a telescope by Galileo.",
  "Your body has about 100 billion neurons.",
  "The first known use of a bicycle pump was in the 1800s.",
  "Some fish can change their gender multiple times.",
  "The first known use of a vending machine was in ancient Greece, dispensing holy water.",
  "The world's most dangerous animal is the mosquito.",
  "The first known use of a stock ticker was in 1867.",
  "Your body has about 200 different types of cells.",
  "The first known use of a smoke detector was in the 1960s.",
  "Some snakes can see infrared (pit vipers).",
  "The first known use of a game console was the Magnavox Odyssey in 1972.",
  "The world's largest flower is Rafflesia (already).",
  "The first known use of a sewing needle was about 25,000 years ago.",
  "Your body has about 25 trillion red blood cells? Actually 20-30 trillion.",
  "The first known use of a mechanical pencil was in 1565.",
  "Some ants can carry objects 50 times their body weight.",
  "The first known use of a pneumatic tire was by John Dunlop in 1887.",
  "The world's longest building is the Great Wall? No, but.",
  "The first known use of a contact lens was by Leonardo da Vinci.",
  "Your body has about 10,000 olfactory receptors? Actually 400 types.",
  "The first known use of a telescope to see Jupiter's moons.",
  "Some fish can survive in water with low oxygen by breathing air.",
  "The first known use of a capacitor was the Leyden jar in 1745.",
  "The world's largest man-made structure is the Great Wall of China (by length).",
  "The first known use of a bicycle chain drive in 1870s.",
  "Your body has about 7,000 taste buds? Let's use 10,000.",
  "The first known use of a steam locomotive in 1804.",
  "Some animals can hibernate for months without eating.",
  "The first known use of a fountain pen in 1827.",
  "The world's largest sinkhole is Xiaozhai Tiankeng in China.",
  "The first known use of a stethoscope was in 1816.",
  "Your body has about 2 million red blood cells produced per second? Actually 2 million per second.",
  "The first known use of a lie detector was in 1921.",
  "Some flowers can generate heat to attract pollinators.",
  "The first known use of a carburetor was in the 19th century.",
  "The world's highest altitude lake is Lake Titicaca? Actually not highest.",
  "The first known use of a margarine was in 1869.",
  "Your body has about 100,000 miles of blood vessels? Actually 60,000.",
  "The first known use of a stun gun was in the 1970s.",
  "Some lizards can walk on water (basilisk lizard).",
  "The first known use of a electric guitar in 1931.",
  "The world's largest statue is the Statue of Unity in India.",
  "The first known use of a car radio was in 1930.",
  "Your body has about 700 muscles? Actually about 600.",
  "The first known use of a fax machine was in 1843.",
  "Some animals can survive without water for years (tardigrades).",
  "The first known use of a bulldozer blade was in the 1920s.",
  "The world's oldest known chess piece is from Jordan, around 700 AD.",
  "The first known use of a solar oven was in the 18th century.",
  "Your body has about 7,000 nerve endings per square inch of skin.",
  "The first known use of a beer can was in 1935.",
  "Some birds can make nests that weigh several tons (bald eagles).",
  "The first known use of a parking lot in 1920s.",
  "The world's tallest waterfall is Angel Falls.",
  "The first known use of a microwave oven in ships?",
  "Your body has about 14 phalanges in each foot.",
  "The first known use of a clock in a church tower in 14th century.",
  "Some snakes can climb trees.",
  "The first known use of a remote control was by Nikola Tesla in 1898.",
  "The world's largest lake entirely in one country is Lake Michigan? Actually not.",
  "The first known use of a snowboard was in 1965.",
  "Your body has about 250,000 sweat glands per foot? Actually.",
  "The first known use of a garage door opener in 1926.",
  "Some fish can breathe air and walk on land (mudskippers).",
  "The first known use of a zipper in clothing in 1913.",
  "The world's largest species of eagle is the Harpy eagle.",
  "The first known use of a flash bulb in photography in 1925.",
  "Your body has about 5 million hair follicles? Actually.",
  "The first known use of a jukebox was in 1889.",
  "Some plants can produce caffeine as a pesticide.",
  "The first known use of a typewriter was in 1868.",
  "The world's fastest bird is the peregrine falcon, diving at 240 mph.",
  "The first known use of a washing machine was in 1851.",
  "Your body has about 2 million pores.",
  "The first known use of a electric fan was in 1882.",
  "Some animals can mimic the sounds of other animals (lyrebird).",
  "The first known use of a ballpoint pen was in 1888.",
  "The world's largest amphitheater is the Colosseum? Actually.",
  "The first known use of a food processor was in the 1940s.",
  "Your body has about 30 trillion cells? Actually 37.2 trillion.",
  "The first known use of a toaster was in 1909.",
  "Some turtles can survive without food for months.",
  "The first known use of a vacuum cleaner was in 1901.",
  "The world's longest railway tunnel is the Gotthard Base Tunnel (57 km).",
  "The first known use of a escalator in a subway in 1911.",
  "Your body has about 10 billion neurons in the brain? Actually 86 billion.",
  "The first known use of a drone was in the 1930s (target drones).",
  "Some flowers can change sex over time.",
  "The first known use of a photocopier was in 1938.",
  "The world's most venomous fish is the stonefish.",
  "The first known use of a dishwashing machine was in 1850.",
  "Your body has about 600 skeletal muscles.",
  "The first known use of a snowplow was in 1923.",
  "Some animals can survive extreme cold by producing antifreeze proteins.",
  "The first known use of a heart transplant was in 1967.",
  "The world's largest aquarium is the Chimelong Ocean Kingdom.",
  "The first known use of a smartphone was the IBM Simon in 1992.",
  "Your body has about 10,000 sweat glands? Actually millions.",
  "The first known use of a touchscreen was in 1965.",
  "Some birds can count eggs in their nests and adjust.",
  "The first known use of a thermostat was in 1883.",
  "The world's oldest known coin is the Lydian lion coin, 600 BC.",
  "The first known use of a seismograph in modern times.",
  "Your body has about 1,000 different types of bacteria? Actually.",
  "The first known use of a birth control pill was in 1960.",
  "Some plants can trap and digest insects (carnivorous plants).",
  "The first known use of a microwave detector was in WWII.",
  "The world's largest palace is the Palace of the Parliament in Romania.",
  "The first known use of a tampon was in ancient Egypt.",
  "Your body has about 500,000 sweat glands? Actually 2-4 million.",
  "The first known use of a fire hose was in 1670s.",
  "Some animals can use tools, like crows and apes.",
  "The first known use of a postage stamp was in 1840 (Penny Black).",
  "The world's largest canyon is the Grand Canyon? Not deepest.",
  "The first known use of a escalator for people was in 1896.",
  "Your body has about 5 million red blood cells per microliter.",
  "The first known use of a laser printer was in 1969.",
  "Some spiders can fly using electrostatic forces.",
  "The first known use of a automatic transmission was in 1904.",
  "The world's deepest cave is Krubera Cave, over 7,000 feet.",
  "The first known use of a hearing aid battery was in 1950s.",
  "Your body has about 60,000 miles of capillaries? Actually.",
  "The first known use of a bulletproof vest was in the 16th century.",
  "Some fish can live in saltwater and freshwater (euryhaline).",
  "The first known use of a blender was in 1922.",
  "The world's longest bridge is the Danyang–Kunshan Grand Bridge.",
  "The first known use of a windsurfing board in 1960s.",
  "Your body has about 2,000 calories of glycogen stored.",
  "The first known use of a digital watch was in 1970.",
  "Some insects can jump 100 times their body length (froghoppers).",
  "The first known use of a steam iron was in 1882.",
  "The world's largest dome is the Pantheon? Actually not largest.",
  "The first known use of a aerosol can was in 1927.",
  "Your body has about 100 trillion bacteria (gut).",
  "The first known use of a spacesuit was in 1961.",
  "Some frogs can survive by absorbing water through skin.",
  "The first known use of a calculator with integrated circuit in 1960s.",
  "The world's largest desert is Antarctica.",
  "The first known use of a water bed was in 1968.",
  "Your body has about 5 liters of blood volume.",
  "The first known use of a snorkel was in ancient Greece.",
  "Some animals can regenerate their entire body from a piece (hydra).",
  "The first known use of a skateboard in 1940s.",
  "The world's tallest tree is Hyperion, a coast redwood, 379 feet.",
  "The first known use of a supersonic aircraft was the Bell X-1 in 1947.",
  "Your body has about 1.5 kg of calcium.",
  "The first known use of a jet ski was in 1960s.",
  "Some plants can produce seeds that survive for thousands of years.",
  "The first known use of a windbreaker jacket in 1940s?",
  "The world's largest oil field is Ghawar in Saudi Arabia.",
  "The first known use of a corkscrew was in the 17th century.",
  "Your body has about 2 million sweat glands? Actually 2-4 million.",
  "The first known use of a paper shredder was in 1909.",
  "Some animals have a third eyelid (nictitating membrane).",
  "The first known use of a smartphone camera was in 2000?",
  "The world's longest tunnel (railway) is Gotthard Base.",
  "The first known use of a snowboard in 1965.",
  "Your body has about 600 lymph nodes? Actually 500-600.",
  "The first known use of a hearing aid with digital processing in 1990s.",
  "Some insects can survive freezing temperatures by producing cryoprotectants.",
  "The first known use of a metal straw in 1990s?",
  "The world's largest library is the Library of Congress.",
  "The first known use of a three-point seatbelt in 1959.",
  "Your body has about 10,000 types of proteins.",
  "The first known use of a selfie stick in 2000s?",
  "Some birds can see Earth's magnetic field (magnetoreception).",
  "The first known use of a centrifuge was in the 19th century.",
  "The world's highest railway is in China, Qinghai-Tibet.",
  "The first known use of a bottle opener was in the 1860s.",
  "Your body has about 0.5% of its mass as minerals? Actually.",
  "The first known use of a mechanical reaper in 1831.",
  "Some sharks can live up to 400 years (Greenland shark).",
  "The first known use of a X-ray machine in 1895.",
  "The world's largest market is the New York Stock Exchange.",
  "The first known use of a forklift was in the 1920s.",
  "Your body has about 100,000 genes? Actually 20,000.",
  "The first known use of a snorkel mask in 1940s?",
  "Some animals can produce silk, like spiders and silkworms.",
  "The first known use of a solar charger in 1950s.",
  "The world's largest dam by volume is Tarbela Dam in Pakistan.",
  "The first known use of a lighter was in 1823 (Döbereiner's lamp).",
  "Your body has about 500 different types of amino acids? Actually 20.",
  "The first known use of a laser barcode scanner in 1974.",
  "Some fish can create electric fields for navigation.",
  "The first known use of a microwave popcorn bag in 1980s.",
  "The world's most populous city is Tokyo.",
  "The first known use of a salad spinner in 1970s.",
  "Your body has about 30,000 genes? Actually ~20,000.",
  "The first known use of a digital thermometer in 1866.",
  "Some plants can close their stomata to conserve water.",
  "The first known use of a water filter in ancient Egypt.",
  "The world's oldest opera house is Teatro San Carlo in Naples.",
  "The first known use of a space pen was in 1965 (Fisher pen).",
  "Your body has about 7 octillion atoms (already).",
  "The first known use of a self-balancing scooter (Segway) in 2001.",
  "Some animals can communicate via dancing (honeybees).",
  "The first known use of a compound bow in 1960s.",
  "The world's tallest building is Burj Khalifa.",
  "The first known use of a electric toothbrush in 1954.",
  "Your body has about 2.5 billion heartbeats in a lifetime? Actually.",
  "The first known use of a personal watercraft in 1970s.",
  "Some fungi can decompose toxic waste.",
  "The first known use of a drone for delivery in 2010s.",
  "The world's largest diamond mine is in Russia.",
  "The first known use of a breathalyzer was in 1954.",
  "Your body has about 100,000 miles of nerve fibers? Actually.",
  "The first known use of a camera with autofocus in 1970s.",
  "Some plants can reproduce via cloning (aspen trees).",
  "The first known use of a touch-tone phone in 1963.",
  "The world's largest artificial lake is Lake Volta.",
  "The first known use of a jetpack was in the 1960s.",
  "Your body has about 20 amino acids required for life.",
  "The first known use of a ski lift was in 1908.",
  "Some animals can change skin color for camouflage (chameleons).",
  "The first known use of a video game console in 1972.",
  "The world's deepest artificial point is the Kola Superdeep Borehole, 40,230 feet.",
  "The first known use of a fireproof safe in the 19th century.",
  "Your body has about 5 million hairs on the body? Actually.",
  "The first known use of a suspension bridge (modern) in 1826.",
  "Some insects can produce sounds by rubbing body parts (stridulation).",
  "The first known use of a USB drive in 2000.",
  "The world's largest port is the Port of Shanghai.",
  "The first known use of a barcode reader was in 1974.",
  "Your body has about 100 trillion synapses.",
  "The first known use of a cat flap was in 1590s.",
  "Some animals have a reflective layer in their eyes (tapetum lucidum).",
  "The first known use of a television remote was in 1950.",
  "The world's highest capital city is La Paz, Bolivia.",
  "The first known use of a electric car in 1834.",
  "Your body has about 2 million red blood cells per second produced? Actually.",
  "The first known use of a tissue paper was in ancient China.",
  "Some plants can detect and respond to sounds.",
  "The first known use of a submarine with a propeller was in 1880s.",
  "The world's oldest known temple is Göbekli Tepe, 11,000 years old.",
  "The first known use of a vending machine for stamps in 1907.",
  "Your body has about 600 skeletal muscles? Actually.",
  "The first known use of a roller coaster was in 1884 (Switchback Railway).",
  "Some fish can produce antifreeze glycoproteins.",
  "The first known use of a water clock in ancient Greece.",
  "The world's largest bookstore is Barnes & Noble? Not sure.",
  "The first known use of a thermostat in homes in the 1880s.",
  "Your body has about 10,000 taste buds? We'll use that.",
  "The first known use of a wood-burning stove in the 16th century.",
  "Some animals can leap 100 times their body length (flea).",
  "The first known use of a jet engine in a car in 1960s.",
  "The world's largest railway station is Grand Central Terminal? Actually.",
  "The first known use of a ball bearing was by Leonardo da Vinci.",
  "Your body has about 50,000 miles of nerves? Actually.",
  "The first known use of a electric blender in 1922.",
  "Some frogs can secrete toxins through skin.",
  "The first known use of a barcode on a product in 1974.",
  "The world's tallest statue is the Statue of Unity.",
  "The first known use of a washing machine with a motor in 1900s.",
  "Your body has about 2 million sweat glands? Let's not.",
  "The first known use of a paper cutter in the 19th century.",
  "Some birds can hover in mid-air (hummingbirds).",
  "The first known use of a electric guitar in 1931.",
  "The world's largest plane is the Antonov An-225 (destroyed).",
  "The first known use of a contact lens for vision correction in 1888.",
  "Your body has about 500 million alveoli in lungs.",
  "The first known use of a smartwatch in 1990s?",
  "Some mammals can live at high altitudes with special hemoglobin.",
  "The first known use of a semiconductor transistor in 1947.",
  "The world's largest hydroelectric dam is the Three Gorges Dam.",
  "The first known use of a escalator in a department store in 1890s.",
  "Your body has about 60,000 miles of blood vessels? I think so.",
  "The first known use of a hair dryer in 1920s.",
  "Some plants can heal wounds by producing resins.",
  "The first known use of a mechanical clock in the 13th century.",
  "The world's largest island (not continent) is Greenland.",
  "The first known use of a fire extinguisher in 1723.",
  "Your body has about 30 trillion cells? Actually.",
  "The first known use of a pedal bicycle in 1860s.",
  "Some animals can sleep with one half of their brain at a time (dolphins).",
  "The first known use of a quartz watch in 1969.",
  "The world's oldest known writing is Sumerian cuneiform.",
  "The first known use of a camera phone in 2000.",
  "Your body has about 250,000 taste buds? Actually 10,000.",
  "The first known use of a drone for military purposes in 1918.",
  "Some fish can produce sounds by vibrating swim bladders.",
  "The first known use of a gas stove in the 1820s.",
  "The world's largest sand desert is the Sahara.",
  "The first known use of a windmill for grinding grain in Persia.",
  "Your body has about 100,000 hairs on the head? Actually.",
  "The first known use of a snow blower in 1920s.",
  "Some insects can live underwater for hours using air bubbles.",
  "The first known use of a digital camera with a memory card in 1995.",
  "The world's tallest fountain is in Jeddah, Saudi Arabia.",
  "The first known use of a lawn sprinkler in the 19th century.",
  "Your body has about 2 million red blood cells produced per second.",
  "The first known use of a can opener was in 1858.",
  "Some animals can regrow their jaw (axolotl).",
  "The first known use of a satellite navigation system was GPS in 1973.",
  "The world's largest cathedral is St. Peter's Basilica? Actually by interior.",
  "The first known use of a mechanical ventilator in 1920s.",
  "Your body has about 10,000 miles of nerve fibers? Actually.",
  "The first known use of a coffee maker was in the 19th century.",
  "Some plants can respond to touch by folding leaves (Mimosa).",
  "The first known use of a robotic arm in 1961.",
  "The world's tallest waterfall is Angel Falls.",
  "The first known use of a LED light in 1962.",
  "Your body has about 2.5 million sweat glands? Actually.",
  "The first known use of a paper towel was in 1907.",
  "Some birds can run on water (basilisk? No, that's lizard).",
  "The first known use of a electric iron in 1882.",
  "The world's deepest lake is Lake Baikal.",
  "The first known use of a zipline was in the 18th century.",
  "Your body has about 5 liters of blood.",
  "The first known use of a geiger counter was in 1908.",
  "Some fish can survive in both salt and fresh water (salmon).",
  "The first known use of a solar water heater in 1890s.",
  "The world's largest salt flat is Salar de Uyuni.",
  "The first known use of a helicopter for rescue in 1944.",
  "Your body has about 37 trillion cells.",
  "The first known use of a screw propeller in 1835.",
  "Some plants can grow in extreme environments (extremophiles).",
  "The first known use of a digital multimeter in 1950s.",
  "The world's oldest cat breed is the Egyptian Mau.",
  "The first known use of a battery-powered clock in 1840s.",
  "Your body has about 206 bones.",
  "The first known use of a water turbine in 1827.",
  "Some animals can produce venom that can kill a human (stonefish).",
  "The first known use of a smoke detector with ionization in 1960s.",
  "The world's largest aquarium tank is in Dubai?",
  "The first known use of a radar detector was in 1960s.",
  "Your body has about 10,000 taste buds? Ok.",
  "The first known use of a corkscrew was in 17th century.",
  "Some insects can produce light to attract mates (fireflies).",
  "The first known use of a mechanical computer by Babbage.",
  "The world's largest railway network is in the US? Actually China.",
  "The first known use of a seatbelt in cars was in 1950s.",
  "Your body has about 600 muscles.",
  "The first known use of a microwave antenna was in radar.",
  "Some animals can hibernate through heat (estivation).",
  "The first known use of a water filter for drinking in 1850s.",
  "The world's longest canal is the Grand Canal in China.",
  "The first known use of a power steering system was in 1951.",
  "Your body has about 100,000 hair follicles on the scalp.",
  "The first known use of a curling iron in the 19th century.",
  "Some fish have transparent heads (barreleye).",
  "The first known use of a pneumatic tube in 1850s.",
  "The world's largest mammal is the blue whale.",
  "The first known use of a heart-lung machine in 1953.",
  "Your body has about 20 amino acids.",
  "The first known use of a solar panel in space in 1958.",
  "Some plants can survive fire by regenerating from roots.",
  "The first known use of a gas mask in 1915.",
  "The world's tallest grass is bamboo.",
  "The first known use of a espresso machine in 1884.",
  "Your body has about 2 million sweat glands? I'll stop.",
  "The first known use of a tire chain in 1904.",
  "Some animals can use echolocation (dolphins, bats).",
  "The first known use of a digital signature in 1970s.",
  "The world's largest prison is in Russia? Actually.",
  "The first known use of a pasta maker in the 19th century.",
  "Your body has about 50 trillion cells? No.",
  "The first known use of a hydraulic press in 1795.",
  "Some birds can mimic chainsaws (lyrebird).",
  "The first known use of a wind turbine for electricity in 1888.",
  "The world's largest amusement park is Disney World? Actually.",
  "The first known use of a camera with color film in 1935.",
  "Your body has about 7,000 nerve endings per square centimeter?",
  "The first known use of a scuba set was in 1943 (Aqua-Lung).",
  "Some plants can move their leaves to track the sun (heliotropism).",
  "The first known use of a biometric fingerprint in 1890s.",
  "The world's largest flower garden is in Netherlands?",
  "The first known use of a jetliner (commercial) in 1952.",
  "Your body has about 300 bones at birth.",
  "The first known use of a can opener was in 1858.",
  "Some fish can change color for camouflage.",
  "The first known use of a computer mouse in 1963.",
  "The world's largest waterfall (by volume) is Inga Falls? Actually.",
  "The first known use of a electric kettle in 1891.",
  "Your body has about 5 million red blood cells per drop?",
  "The first known use of a parking meter in 1935.",
  "Some insects can run on water (water striders).",
  "The first known use of a centrifuge in 1864.",
  "The world's tallest sand dune is in the Namib Desert.",
  "The first known use of a self-driving car in 1980s.",
  "Your body has about 1.5 kg of bones? Actually.",
  "The first known use of a metal detector for security in 1970s.",
  "Some animals can produce electric fields (electric eel).",
  "The first known use of a digital audio player (MP3) in 1998.",
  "The world's largest dome is the Pantheon? Actually.",
  "The first known use of a fishing net was in ancient times.",
  "Your body has about 100 billion neurons? Actually 86 billion.",
  "The first known use of a water bed was in 1968.",
  "Some plants can live for thousands of years (bristlecone pine).",
  "The first known use of a mechanical reaper was in 1831.",
  "The world's largest lake (by area) is the Caspian Sea.",
  "The first known use of a glow stick was in 1960s.",
  "Your body has about 2.5 million red blood cells per second?",
  "The first known use of a airplane toilet was in 1920s.",
  "Some fish can survive in oxygen-depleted water by breathing air.",
  "The first known use of a digital thermometer was in 1866.",
  "The world's largest shipping container ship is the MSC Gülsün.",
  "The first known use of a car alarm was in 1920s.",
  "Your body has about 10,000 miles of capillaries? Actually.",
  "The first known use of a snowshoe was in ancient times.",
  "Some animals can detect seismic vibrations (elephants).",
  "The first known use of a modern zipper in 1913.",
  "The world's highest road is in Tibet.",
  "The first known use of a coffee grinder in the 15th century.",
  "Your body has about 60,000 miles of blood vessels? I'll trust.",
  "The first known use of a electric dishwasher in 1886.",
  "Some plants can mimic the smell of rotting meat to attract flies.",
  "The first known use of a seismometer in 132 AD.",
  "The world's largest stadium is Rungrado 1st of May Stadium.",
  "The first known use of a windbreaker in 1940s.",
  "Your body has about 2 million red blood cells per second? Already.",
  "The first known use of a selfie was in 1839 (Robert Cornelius).",
  "Some animals can produce bioluminescent light (anglerfish).",
  "The first known use of a digital watch in 1970.",
  "The world's tallest man-made structure is Burj Khalifa.",
  "The first known use of a battery-powered drill in 1917.",
  "Your body has about 100,000 miles of nerves? Actually.",
  "The first known use of a paper cup was in 1908.",
  "Some insects can undergo complete metamorphosis (butterflies).",
  "The first known use of a sewing machine with electric motor in 1889.",
  "The world's largest basilica is St. Peter's?",
  "The first known use of a shaving razor in 1901 (Gillette).",
  "Your body has about 2.5 million sweat glands? I'll stop.",
  "The first known use of a headlamp in 1880s.",
  "Some animals can survive extreme radiation (tardigrades).",
  "The first known use of a parallel computer in 1960s.",
  "The world's largest cave chamber is in Son Doong.",
  "The first known use of a hand dryer in 1940s.",
  "Your body has about 10 trillion cells? Actually more.",
  "The first known use of a pressure cooker was in 1679.",
  "Some plants can produce latex.",
  "The first known use of a solar cell in 1883.",
  "The world's largest artificial island is Palm Jumeirah.",
  "The first known use of a defibrillator in 1930s.",
  "Your body has about 0.2 mg of gold.",
  "The first known use of a pull-tab can in 1962.",
  "Some fish can produce sound by grinding teeth.",
  "The first known use of a electric lawnmower in 1938.",
  "The world's longest coast is Canada's.",
  "The first known use of a hydraulic lift in 1846.",
  "Your body has about 100,000 miles of blood vessels? yes.",
  "The first known use of a barcode scanner in 1974.",
  "Some animals can see polarized light (bees).",
  "The first known use of a dishwasher in 1886.",
  "The world's largest volcano is Mauna Loa.",
  "The first known use of a skateboard in 1940s.",
  "Your body has about 600 muscles.",
  "The first known use of a space shuttle in 1981.",
  "Some plants can store water (succulents).",
  "The first known use of a microwave oven in 1946.",
  "The world's largest river by discharge is the Amazon.",
  "The first known use of a sewing machine in 1790.",
  "Your body has about 5 liters of blood.",
  "The first known use of a suspension bridge in 1800s.",
  "Some animals can regenerate their tails (lizards).",
  "The first known use of a telephone in 1876.",
  "The world's largest mountain range is the mid-ocean ridge.",
  "The first known use of a camera in 1816.",
  "Your body has about 206 bones.",
  "The first known use of a computer mouse in 1963.",
  "Some birds can recognize human faces (crows).",
  "The first known use of a drone in 1917.",
  "The world's largest desert is Antarctica.",
  "The first known use of a jet engine in 1939.",
  "Your body has about 100 trillion cells.",
  "The first known use of a ketchup was in 1812.",
  "Some mushrooms can communicate via mycelium.",
  "The first known use of a light bulb by Edison in 1879.",
  "The world's largest island is Greenland.",
  "The first known use of a map in 600 BC.",
  "Your body has about 20,000 genes.",
  "The first known use of a newspaper in 1605.",
  "Some fish can fly (flying fish) for short distances.",
  "The first known use of a ocean liner in 1840s.",
  "The world's largest pyramid is the Great Pyramid of Cholula.",
  "The first known use of a parachute in 1783.",
  "Your body has about 37 trillion cells.",
  "The first known use of a quartz clock in 1927.",
  "Some animals can regenerate their liver (humans too).",
  "The first known use of a radio in 1895.",
  "The world's largest reef is the Great Barrier Reef.",
  "The first known use of a rocket in 1232 (Chinese).",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a satellite in 1957.",
  "Some plants can close their flowers at night.",
  "The first known use of a sprinkler in 1870s.",
  "The world's largest statue is the Statue of Unity.",
  "The first known use of a submarine in 1620.",
  "Your body has about 100 billion neurons? Actually 86 billion.",
  "The first known use of a thermometer in 1593.",
  "Some animals can survive in space (tardigrades).",
  "The first known use of a tractor in 1892.",
  "The world's largest tree by volume is General Sherman.",
  "The first known use of a vacuum cleaner in 1901.",
  "Your body has about 2 million sweat glands? I'll stop here.",
  "The first known use of a washing machine in 1851.",
  "Some insects can carry 50 times their weight (ants).",
  "The first known use of a water wheel in ancient Greece.",
  "The world's longest river is the Nile.",
  "The first known use of a windmill in 500 AD.",
  "Your body has about 5 million hairs.",
  "The first known use of a X-ray in 1895.",
  "Some animals can detect magnetic fields (migratory birds).",
  "The first known use of a yo-yo in 440 BC.",
  "The world's tallest animal is the giraffe.",
  "The first known use of a zipper in 1893.",
  "Your body has about 0.2 mg of gold.",
  "The first known use of a camera obscura in 1021.",
  "Some plants can grow in saltwater (mangroves).",
  "The first known use of a diving bell in 1535.",
  "The world's largest airport is King Fahd International.",
  "The first known use of a electric fan in 1882.",
  "Your body has about 100,000 miles of capillaries? Actually.",
  "The first known use of a fire engine in 18th century.",
  "Some birds can sleep while flying (albatross).",
  "The first known use of a guitar in 1500s.",
  "The world's largest freshwater lake by volume is Baikal.",
  "The first known use of a helicopter in 1939.",
  "Your body has about 10,000 taste buds.",
  "The first known use of a ice cream maker in 1843.",
  "Some fish can survive in Antarctic waters with antifreeze.",
  "The first known use of a jet pack in 1960s.",
  "The world's largest desert (hot) is Sahara.",
  "The first known use of a lawnmower in 1830.",
  "Your body has about 600 muscles.",
  "The first known use of a microscope in 1590.",
  "Some animals can change sex (clownfish).",
  "The first known use of a motorcycle in 1885.",
  "The world's tallest building is Burj Khalifa.",
  "The first known use of a noodle in 4000 BC China.",
  "Your body has about 206 bones.",
  "The first known use of a oil lamp in 70,000 BC.",
  "Some plants can mimic other plants (Batesian mimicry).",
  "The first known use of a paperclip in 1899.",
  "The world's largest whale is the blue whale.",
  "The first known use of a parachute in 1783.",
  "Your body has about 100 trillion cells.",
  "The first known use of a periscope in 1854.",
  "Some insects can survive extreme heat (desert beetles).",
  "The first known use of a phonograph in 1877.",
  "The world's longest bridge is Danyang–Kunshan.",
  "The first known use of a piano in 1700.",
  "Your body has about 5 liters of blood.",
  "The first known use of a pizza oven in 19th century.",
  "Some animals can produce silk (spiders).",
  "The first known use of a printing press in 1440.",
  "The world's largest crater is Vredefort in South Africa.",
  "The first known use of a pulley in 1500 BC.",
  "Your body has about 20 amino acids.",
  "The first known use of a quartz watch in 1969.",
  "Some plants can produce caffeine as a defense.",
  "The first known use of a radio telescope in 1937.",
  "The world's deepest mine is Mponeng in South Africa.",
  "The first known use of a refrigerator in 1805.",
  "Your body has about 37 trillion cells.",
  "The first known use of a robot word in 1920s.",
  "Some fish can breathe air (lungfish).",
  "The first known use of a rocket in 1232.",
  "The world's largest stadium by capacity is in North Korea.",
  "The first known use of a rubber band in 1845.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a safety razor in 1880.",
  "Some animals can live in boiling water (thermophiles).",
  "The first known use of a satellite in 1957.",
  "The world's tallest statue is the Statue of Unity.",
  "The first known use of a sewing needle in 25,000 BC.",
  "Your body has about 100 billion neurons.",
  "The first known use of a shower in 300 BC.",
  "Some plants can defend themselves with thorns.",
  "The first known use of a siphon in 400 BC.",
  "The world's largest lake is Caspian Sea.",
  "The first known use of a skateboard in 1940s.",
  "Your body has about 2 million red blood cells per second.",
  "The first known use of a smartphone in 1992.",
  "Some birds can mimic human speech (parrots).",
  "The first known use of a snowboard in 1965.",
  "The world's longest railway is Trans-Siberian.",
  "The first known use of a solar cell in 1883.",
  "Your body has about 10,000 taste buds.",
  "The first known use of a spacesuit in 1961.",
  "Some insects can fly at 35 mph (dragonfly).",
  "The first known use of a steam engine in 1712.",
  "The world's largest spider is Goliath birdeater.",
  "The first known use of a stethoscope in 1816.",
  "Your body has about 5 million hairs.",
  "The first known use of a submarine in 1620.",
  "Some animals can see ultraviolet light (bees).",
  "The first known use of a telephone in 1876.",
  "The world's tallest waterfall is Angel Falls.",
  "The first known use of a telescope in 1608.",
  "Your body has about 206 bones.",
  "The first known use of a television in 1927.",
  "Some plants can grow in arid conditions (cacti).",
  "The first known use of a thermometer in 1593.",
  "The world's largest turtle is the leatherback sea turtle.",
  "The first known use of a toilet in 2600 BC.",
  "Your body has about 37 trillion cells.",
  "The first known use of a toothbrush in 600 AD.",
  "Some fish can produce electric shocks (electric eel).",
  "The first known use of a tractor in 1892.",
  "The world's longest tunnel is Gotthard Base.",
  "The first known use of a traffic light in 1868.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a vacuum cleaner in 1901.",
  "Some birds can fly for months without landing (swifts).",
  "The first known use of a washing machine in 1851.",
  "The world's largest volcano is Mauna Loa.",
  "The first known use of a watch in 1500s.",
  "Your body has about 100 trillion cells.",
  "The first known use of a wheelchair in 5th century China.",
  "Some insects can produce sounds by stridulation.",
  "The first known use of a wind turbine in 1888.",
  "The world's deepest canyon is Yarlung Tsangpo.",
  "The first known use of a X-ray in 1895.",
  "Your body has about 20,000 genes.",
  "The first known use of a yo-yo in 440 BC.",
  "Some animals can regenerate limbs (axolotl).",
  "The first known use of a zipper in 1893.",
  "The world's tallest mountain is Everest.",
  "The first known use of a alarm clock in 1787.",
  "Your body has about 206 bones.",
  "The first known use of a bicycle in 1817.",
  "Some plants can produce poison (oleander).",
  "The first known use of a camera in 1816.",
  "The world's largest river by volume is Amazon.",
  "The first known use of a compass in 11th century.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a escalator in 1891.",
  "Some animals can survive without food for months (snakes).",
  "The first known use of a fire extinguisher in 1723.",
  "The world's tallest building is Burj Khalifa.",
  "The first known use of a fountain pen in 10th century.",
  "Your body has about 5 liters of blood.",
  "The first known use of a guitar in 1500s.",
  "Some insects can jump 100 times their length.",
  "The first known use of a helicopter in 1939.",
  "The world's largest island is Greenland.",
  "The first known use of a hot air balloon in 1783.",
  "Your body has about 37 trillion cells.",
  "The first known use of a jet engine in 1939.",
  "Some plants can grow in extreme cold (Arctic willow).",
  "The first known use of a kite in 500 BC.",
  "The world's longest bridge is Danyang–Kunshan.",
  "The first known use of a laser in 1960.",
  "Your body has about 100 billion neurons.",
  "The first known use of a lawnmower in 1830.",
  "Some animals can camouflage (octopus).",
  "The first known use of a light bulb in 1879.",
  "The world's largest mammal is blue whale.",
  "The first known use of a match in 1826.",
  "Your body has about 206 bones.",
  "The first known use of a microscope in 1590.",
  "Some fish can live out of water (lungfish).",
  "The first known use of a microwave in 1946.",
  "The world's tallest tree is Hyperion.",
  "The first known use of a motorcar in 1886.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a parachute in 1783.",
  "Some plants can close their leaves at night.",
  "The first known use of a pencil in 1565.",
  "The world's largest desert is Antarctica.",
  "The first known use of a piano in 1700.",
  "Your body has about 100 trillion cells.",
  "The first known use of a printing press in 1440.",
  "Some animals can use tools (crows).",
  "The first known use of a radio in 1895.",
  "The world's deepest point is Mariana Trench.",
  "The first known use of a rocket in 1232.",
  "Your body has about 20,000 genes.",
  "The first known use of a satellite in 1957.",
  "Some insects can create light (fireflies).",
  "The first known use of a sewing machine in 1790.",
  "The world's largest statue is Statue of Unity.",
  "The first known use of a ship in 3000 BC.",
  "Your body has about 5 liters of blood.",
  "The first known use of a telephone in 1876.",
  "Some plants can produce edible fruits.",
  "The first known use of a television in 1927.",
  "The world's tallest waterfall is Angel Falls.",
  "The first known use of a telescope in 1608.",
  "Your body has about 206 bones.",
  "The first known use of a toilet in 2600 BC.",
  "Some animals can fly (birds).",
  "The first known use of a toothbrush in 600 AD.",
  "The world's longest river is Nile.",
  "The first known use of a train in 1804.",
  "Your body has about 37 trillion cells.",
  "The first known use of a typewriter in 1868.",
  "Some fish can glow (anglerfish).",
  "The first known use of a umbrella in 4,000 years ago.",
  "The world's largest cave is Son Doong.",
  "The first known use of a vacuum cleaner in 1901.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a washing machine in 1851.",
  "Some birds can mimic sounds (lyrebird).",
  "The first known use of a watch in 1500s.",
  "The world's highest mountain is Everest.",
  "The first known use of a wheelchair in 5th century.",
  "Your body has about 100 billion neurons.",
  "The first known use of a windmill in 500 AD.",
  "Some plants can survive fire.",
  "The first known use of a X-ray in 1895.",
  "The world's largest ocean is Pacific.",
  "The first known use of a yo-yo in 440 BC.",
  "Your body has about 206 bones.",
  "The first known use of a zipper in 1893.",
  "Some animals can regenerate (starfish).",
  "The first known use of a airplane in 1903.",
  "The world's tallest building is Burj Khalifa.",
  "The first known use of a alarm clock in 1787.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a bicycle in 1817.",
  "Some fish can change sex (clownfish).",
  "The first known use of a camera in 1816.",
  "The world's largest reptile is crocodile.",
  "The first known use of a compass in 11th century.",
  "Your body has about 100 trillion cells.",
  "The first known use of a computer in 1945.",
  "Some plants can eat insects (Venus flytrap).",
  "The first known use of a escalator in 1891.",
  "The world's largest bird is ostrich.",
  "The first known use of a fire extinguisher in 1723.",
  "Your body has about 5 liters of blood.",
  "The first known use of a fountain pen in 10th century.",
  "Some animals can hibernate (bears).",
  "The first known use of a guitar in 1500s.",
  "The world's tallest animal is giraffe.",
  "The first known use of a helicopter in 1939.",
  "Your body has about 206 bones.",
  "The first known use of a hot air balloon in 1783.",
  "Some insects can jump (fleas).",
  "The first known use of a jet engine in 1939.",
  "The world's largest island is Greenland.",
  "The first known use of a laser in 1960.",
  "Your body has about 37 trillion cells.",
  "The first known use of a lawnmower in 1830.",
  "Some fish can produce electricity (electric eel).",
  "The first known use of a light bulb in 1879.",
  "The world's largest mammal is blue whale.",
  "The first known use of a match in 1826.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a microscope in 1590.",
  "Some plants can move (Mimosa).",
  "The first known use of a microwave in 1946.",
  "The world's tallest tree is Hyperion.",
  "The first known use of a motorcar in 1886.",
  "Your body has about 100 billion neurons.",
  "The first known use of a parachute in 1783.",
  "Some animals can fly (bats).",
  "The first known use of a pencil in 1565.",
  "The world's largest desert is Antarctica.",
  "The first known use of a piano in 1700.",
  "Your body has about 206 bones.",
  "The first known use of a printing press in 1440.",
  "Some insects can communicate (bees).",
  "The first known use of a radio in 1895.",
  "The world's deepest point is Mariana Trench.",
  "The first known use of a rocket in 1232.",
  "Your body has about 20,000 genes.",
  "The first known use of a satellite in 1957.",
  "Some plants can produce toxins.",
  "The first known use of a sewing machine in 1790.",
  "The world's largest statue is Statue of Unity.",
  "The first known use of a ship in 3000 BC.",
  "Your body has about 5 liters of blood.",
  "The first known use of a telephone in 1876.",
  "Some animals can see in the dark (owls).",
  "The first known use of a television in 1927.",
  "The world's tallest waterfall is Angel Falls.",
  "The first known use of a telescope in 1608.",
  "Your body has about 37 trillion cells.",
  "The first known use of a toilet in 2600 BC.",
  "Some fish can breathe air.",
  "The first known use of a toothbrush in 600 AD.",
  "The world's longest river is Nile.",
  "The first known use of a train in 1804.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a typewriter in 1868.",
  "Some birds can mimic (lyrebird).",
  "The first known use of a umbrella in 4,000 years ago.",
  "The world's largest cave is Son Doong.",
  "The first known use of a vacuum cleaner in 1901.",
  "Your body has about 206 bones.",
  "The first known use of a washing machine in 1851.",
  "Some plants can live in deserts.",
  "The first known use of a watch in 1500s.",
  "The world's highest mountain is Everest.",
  "The first known use of a wheelchair in 5th century.",
  "Your body has about 100 billion neurons.",
  "The first known use of a windmill in 500 AD.",
  "Some animals can regenerate (starfish).",
  "The first known use of a X-ray in 1895.",
  "The world's largest ocean is Pacific.",
  "The first known use of a yo-yo in 440 BC.",
  "Your body has about 5 liters of blood.",
  "The first known use of a zipper in 1893.",
  "Some insects can fly (dragonflies).",
  "The first known use of a airplane in 1903.",
  "The world's tallest building is Burj Khalifa.",
  "The first known use of a alarm clock in 1787.",
  "Your body has about 37 trillion cells.",
  "The first known use of a bicycle in 1817.",
  "Some fish can glow (anglerfish).",
  "The first known use of a camera in 1816.",
  "The world's largest reptile is crocodile.",
  "The first known use of a compass in 11th century.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a computer in 1945.",
  "Some plants can eat insects.",
  "The first known use of a escalator in 1891.",
  "The world's largest bird is ostrich.",
  "The first known use of a fire extinguisher in 1723.",
  "Your body has about 206 bones.",
  "The first known use of a fountain pen in 10th century.",
  "Some animals can hibernate.",
  "The first known use of a guitar in 1500s.",
  "The world's tallest animal is giraffe.",
  "The first known use of a helicopter in 1939.",
  "Your body has about 100 billion neurons.",
  "The first known use of a hot air balloon in 1783.",
  "Some insects can jump.",
  "The first known use of a jet engine in 1939.",
  "The world's largest island is Greenland.",
  "The first known use of a laser in 1960.",
  "Your body has about 5 liters of blood.",
  "The first known use of a lawnmower in 1830.",
  "Some fish can produce electricity.",
  "The first known use of a light bulb in 1879.",
  "The world's largest mammal is blue whale.",
  "The first known use of a match in 1826.",
  "Your body has about 37 trillion cells.",
  "The first known use of a microscope in 1590.",
  "Some plants can move.",
  "The first known use of a microwave in 1946.",
  "The world's tallest tree is Hyperion.",
  "The first known use of a motorcar in 1886.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a parachute in 1783.",
  "Some animals can fly.",
  "The first known use of a pencil in 1565.",
  "The world's largest desert is Antarctica.",
  "The first known use of a piano in 1700.",
  "Your body has about 206 bones.",
  "The first known use of a printing press in 1440.",
  "Some insects can communicate.",
  "The first known use of a radio in 1895.",
  "The world's deepest point is Mariana Trench.",
  "The first known use of a rocket in 1232.",
  "Your body has about 100 billion neurons.",
  "The first known use of a satellite in 1957.",
  "Some plants can produce toxins.",
  "The first known use of a sewing machine in 1790.",
  "The world's largest statue is Statue of Unity.",
  "The first known use of a ship in 3000 BC.",
  "Your body has about 5 liters of blood.",
  "The first known use of a telephone in 1876.",
  "Some animals can see in the dark.",
  "The first known use of a television in 1927.",
  "The world's tallest waterfall is Angel Falls.",
  "The first known use of a telescope in 1608.",
  "Your body has about 37 trillion cells.",
  "The first known use of a toilet in 2600 BC.",
  "Some fish can breathe air.",
  "The first known use of a toothbrush in 600 AD.",
  "The world's longest river is Nile.",
  "The first known use of a train in 1804.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a typewriter in 1868.",
  "Some birds can mimic.",
  "The first known use of a umbrella in 4,000 years ago.",
  "The world's largest cave is Son Doong.",
  "The first known use of a vacuum cleaner in 1901.",
  "Your body has about 206 bones.",
  "The first known use of a washing machine in 1851.",
  "Some plants can live in deserts.",
  "The first known use of a watch in 1500s.",
  "The world's highest mountain is Everest.",
  "The first known use of a wheelchair in 5th century.",
  "Your body has about 100 billion neurons.",
  "The first known use of a windmill in 500 AD.",
  "Some animals can regenerate.",
  "The first known use of a X-ray in 1895.",
  "The world's largest ocean is Pacific.",
  "The first known use of a yo-yo in 440 BC.",
  "Your body has about 5 liters of blood.",
  "The first known use of a zipper in 1893.",
  "Some insects can fly.",
  "The first known use of a airplane in 1903.",
  "The world's tallest building is Burj Khalifa.",
  "The first known use of a alarm clock in 1787.",
  "Your body has about 37 trillion cells.",
  "The first known use of a bicycle in 1817.",
  "Some fish can glow.",
  "The first known use of a camera in 1816.",
  "The world's largest reptile is crocodile.",
  "The first known use of a compass in 11th century.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a computer in 1945.",
  "Some plants can eat insects.",
  "The first known use of a escalator in 1891.",
  "The world's largest bird is ostrich.",
  "The first known use of a fire extinguisher in 1723.",
  "Your body has about 206 bones.",
  "The first known use of a fountain pen in 10th century.",
  "Some animals can hibernate.",
  "The first known use of a guitar in 1500s.",
  "The world's tallest animal is giraffe.",
  "The first known use of a helicopter in 1939.",
  "Your body has about 100 billion neurons.",
  "The first known use of a hot air balloon in 1783.",
  "Some insects can jump.",
  "The first known use of a jet engine in 1939.",
  "The world's largest island is Greenland.",
  "The first known use of a laser in 1960.",
  "Your body has about 5 liters of blood.",
  "The first known use of a lawnmower in 1830.",
  "Some fish can produce electricity.",
  "The first known use of a light bulb in 1879.",
  "The world's largest mammal is blue whale.",
  "The first known use of a match in 1826.",
  "Your body has about 37 trillion cells.",
  "The first known use of a microscope in 1590.",
  "Some plants can move.",
  "The first known use of a microwave in 1946.",
  "The world's tallest tree is Hyperion.",
  "The first known use of a motorcar in 1886.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a parachute in 1783.",
  "Some animals can fly.",
  "The first known use of a pencil in 1565.",
  "The world's largest desert is Antarctica.",
  "The first known use of a piano in 1700.",
  "Your body has about 206 bones.",
  "The first known use of a printing press in 1440.",
  "Some insects can communicate.",
  "The first known use of a radio in 1895.",
  "The world's deepest point is Mariana Trench.",
  "The first known use of a rocket in 1232.",
  "Your body has about 100 billion neurons.",
  "The first known use of a satellite in 1957.",
  "Some plants can produce toxins.",
  "The first known use of a sewing machine in 1790.",
  "The world's largest statue is Statue of Unity.",
  "The first known use of a ship in 3000 BC.",
  "Your body has about 5 liters of blood.",
  "The first known use of a telephone in 1876.",
  "Some animals can see in the dark.",
  "The first known use of a television in 1927.",
  "The world's tallest waterfall is Angel Falls.",
  "The first known use of a telescope in 1608.",
  "Your body has about 37 trillion cells.",
  "The first known use of a toilet in 2600 BC.",
  "Some fish can breathe air.",
  "The first known use of a toothbrush in 600 AD.",
  "The world's longest river is Nile.",
  "The first known use of a train in 1804.",
  "Your body has about 60,000 miles of blood vessels.",
  "The first known use of a typewriter in 1868.",
  "Some birds can mimic.",
  "The first known use of a umbrella in 4,000 years ago.",
  "The world's largest cave is Son Doong.",
  "The first known use of a vacuum cleaner in 1901.",
  "Your body has about 206 bones.",
  "The first known use of a washing machine in 1851.",
  "Some plants can live in deserts.",
  "The first known use of a watch in 1500s.",
  "The world's highest mountain is Everest.",
  "The first known use of a wheelchair in 5th century.",
  "Your body has about 100 billion neurons.",
  "The first known use of a windmill in 500 AD.",
  "Some animals can regenerate.",
  "The first known use of a X-ray in 1895.",
  "The world's largest ocean is Pacific.",
  "The first known use of a yo-yo in 440 BC.",
  "Your body has about 5 liters of blood.",
  "The first known use of a zipper in 1893."
];